version: '3'

services:
  queued_flask_app:
    build: .
    image: queued_flask_app
    container_name: queued_flask_app
    entrypoint: python manage.py run -h 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=app.config.DevelopmentConfig
    depends_on:
      - redis
  
  worker:
    image: queued_flask_app
    container_name: queued_flask_app_worker
    entrypoint: python manage.py run_worker
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
    volumes:
      - .:/usr/src
    depends_on:
      - redis

  redis:
    container_name: redis_cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    
volumes:
  redis:
    driver: local
  
